(defunhb pi)
(defunhb sin N)
(defunhb cos N)
(defunhb tan N)
(defunhb cot N)
(defunhb asin N)
(defunhb acos N)
(defunhb atan N)
(defunhb rtod N)
(defunhb dtor N)
(defunhb exp N)
(defunhb log N)
(defunhb log10 N)
(defunhb sqrt N)
(defunhb floor N)
(defunhb ceiling N)
(defunhb round NN)
(defunhb substr CNN)
(defunhb hb_at CCNN)
(defunhb date)
(defunhb time)
(defunhb seconds)
(defunhb day D)
(defunhb cmonth D)
(defunhb month D)
(defunhb year D)
(defunhb curdir)
(defunhb file C)
(defunhb memoread C)
(defunhb memowrit CC)